version: '3.8'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:

secrets:
  POSTGRES_USER:
    file: ./secrets.yml
  POSTGRES_PASSWORD:
    file: ./secrets.yml
  POSTGRES_DB:
    file: ./secrets.yml