apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER:  #base64 value
  POSTGRES_PASSWORD:  #base64 value
  POSTGRES_DB:  #base64 value
  POSTGRES_HOST:  #base64 value
