apiVersion: v1
kind: Service #A service is a method for exposing a pod to the outside world.
metadata:
  name: test-app
spec:
  selector:
    app: test-app #Name of deployment the service refers to
  ports:
    - protocol: TCP
      port: 8080 #Port on which the service will listen.
      targetPort: 8080 #Port to which the service will redirect the traffic.
  type: LoadBalancer #Type of service.
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP #Expose the service internally only.
  ports:
   - port: 5432
  selector:
   app: postgres